# -*- mode: ruby -*-

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define 'local', primary: true do |local|
    local.vm.box = "hashicorp/precise32"
    
    local.vm.network "forwarded_port", guest: 9090, host: 9090
    local.vm.network "forwarded_port", guest: 5222, host: 5222
    local.vm.network "forwarded_port", guest: 8080, host: 8080

    local.vm.provision "puppet" do |puppet|
      puppet.manifests_path = "puppet/manifests"
      puppet.module_path = "puppet/modules"
      puppet.manifest_file  = "local.pp"
    end
  end
end
